[token.NAM]
# this always needs to be present for our tooling to work
tnam1qz4u7j7dkxj5wv9xuwy2qemaeeqd450ysgl7pq0r = "1000000000"

[token.BTC]
tnam1qz4u7j7dkxj5wv9xuwy2qemaeeqd450ysgl7pq0r = "1000000000"

[token.ETH]
tnam1qz4u7j7dkxj5wv9xuwy2qemaeeqd450ysgl7pq0r = "1000000000"
