# General protocol parameters.
[parameters]
native_token = "NAAN"
is_native_token_transferable = true
# Minimum number of blocks in an epoch.
# This should be 10 hours given that blocks are on average 10 seconds. ( (10*60*60)/10 )
min_num_of_blocks = 12
# Maximum expected time per block (in seconds).
max_expected_time_per_block = 10
# Max payload size, in bytes, for a tx.
max_tx_bytes = 1048576
# Max payload size, in bytes, for a tx batch proposal.
max_proposal_bytes = 6291456
# vp allowlist
vp_allowlist = []
# tx allowlist
tx_allowlist = []
# Implicit VP WASM name
implicit_vp = "vp_implicit"
# Expected number of epochs per year (also sets the min duration of an epoch in seconds)
# Epochs should be 12 hours. ( (365*24*60*60)/(12*60*60) )
# Epochs set to last 2 minutes
epochs_per_year = 262800
# Maximum number of signature per transaction
max_signatures_per_transaction = 15
# Max gas for block
max_block_gas = 5000000
# Fee unshielding gas limit
fee_unshielding_gas_limit = 20000
# Fee unshielding descriptions limit
fee_unshielding_descriptions_limit = 15

# Map of the cost per gas unit for every token allowed for fee payment
[parameters.minimum_gas_price]
# assumes that an avg tx takes 10,000 gas, this means that a tx cost 1 naan
# 10,000 * 0.0001
naan = "0.0001"

# Proof of stake parameters.
[pos_params]
# Maximum number of active validators.
max_validator_slots = 257
# Pipeline length (in epochs). Any change in the validator set made in
# epoch 'n' will become active in epoch 'n + pipeline_len'.
pipeline_len = 2
# Unbonding length (in epochs). Validators may have their stake slashed
# for a fault in epoch 'n' up through epoch 'n + unbonding_len'.
# 2 days for unbonding
# unbonding is actually unbonding_len + cubic_slashing_window_length so 2.5 days
unbonding_len = 4
# Votes per fundamental staking token (namnam)
tm_votes_per_token = "1"
# Reward for proposing a block.
block_proposer_reward = "0.125"
# Reward for voting on a block.
block_vote_reward = "0.1"
# Maximum inflation rate per annum (10%)
# start with 0 inflation
max_inflation_rate = "0.0"
# Targeted ratio of staked tokens to total tokens in the supply
target_staked_ratio = "0.0"
# Portion of a validator's stake that should be slashed on a duplicate
# vote.
duplicate_vote_min_slash_rate = "0.001"
# Portion of a validator's stake that should be slashed on a light
# client attack.
light_client_attack_min_slash_rate = "0.001"
# Number of epochs above and below (separately) the current epoch to
# consider when doing cubic slashing
cubic_slashing_window_length = 1
# The minimum amount of bonded tokens that a validator needs to be in
# either the `consensus` or `below_capacity` validator sets
# A validator should have at least 0.01% of the total tokens to be considered active.
validator_stake_threshold = "1000"
# The length, in blocks, of the sliding window for consensus validators
# inactivity verification
# Liveness window is 24 hours.
liveness_window_check = 8_640
# The minimum required activity of consensus validators, in percentage, over 
# the `liveness_window_check`
liveness_threshold = "0.9"
# The P gain factor in the Proof of Stake rewards controller
rewards_gain_p = "0.0"
# The D gain factor in the Proof of Stake rewards controller
rewards_gain_d = "0.0"

# Governance parameters.
[gov_params]
# minimum amount of naan token to lock
min_proposal_fund = 5000
# proposal code size in bytes
max_proposal_code_size = 600000
# min proposal period length in epochs
# 1 day minimum
min_proposal_voting_period = 2
# max proposal period length in epochs
# 2 days maximum
max_proposal_period = 6
# maximum number of characters in the proposal content
max_proposal_content_size = 10000
# minimum epochs between end and grace epoch
# 1 day grace period
min_proposal_grace_epochs = 2

# Public goods funding parameters
[pgf_params]
# Initial set of stewards
stewards = []
# The pgf funding inflation rate
pgf_inflation_rate = "0.0"
# The pgf stewards inflation rate
stewards_inflation_rate = "0.0"

# IBC parameters
[ibc_params]
# default mint limit of each token
default_mint_limit = "0"
# default per-epoch throughput limit of each token
default_per_epoch_throughput_limit = "0"