[token.NAM]
# this always needs to be present for our tooling to work
tpknam1qzvszv50azclqa05reqveehkwknpl4kh6tn3vajpt0vusa8mjpluk89ac03 = "1000000"
# this always needs to be present for our tooling to work
tnam1qz4u7j7dkxj5wv9xuwy2qemaeeqd450ysgl7pq0r = "1000000"

